# dont override colors
set-option -sa terminal-overrides ",xterm*:Tc"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-yank'

### Tokyo Night Theme configuration
set -g @powerkit_theme 'tokyo-night'
set -g @powerkit_theme_variant 'night'
set -g @powerkit_plugins 'datetime,battery,cpu,memory'
set -g @powerkit_plugin_datetime_format '%H:%M'
set -g @powerkit_status_position 'bottom'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

#remaps
# Unbind default key bindings
unbind '"' # Vertical split 
unbind '%' # Horizontal split 

# Set new bindings for splits
bind h split-window -v -c "#{pane_current_path}"  # Vertical split (Leader+h)
bind v split-window -h -c "#{pane_current_path}"  # Horizontal split (Leader+v)

bind c new-window -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


